#!/usr/bin/env bash
# Install nginx on a server, and serve a simple html page
# with the text "Hello World!"

sudo apt-get update;

sudo apt-get install -y nginx;

sudo ufw allow "Nginx HTTP";

# restart nginx
sudo service nginx restart;

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html';