#!/usr/bin/env bash
# Create a compressed backup file for all databases on a server

date_form=$(date +"%d-%m-%Y")
archive=$date_form.tar.gz
password=$1
file='backup.sql'
sudo mysqldump -p '$password' --all-databases > $file;
tar -cvzf $archive $file
