#!/usr/bin/env bash
# Find out what’s keeping an Ubuntu container’s Nginx
# installation from listening on port 80

# update package index
apt update &>/dev/null;

# install lsof a helpful and easy to use tool
if ! which lsof &>/dev/null; then
    apt install lsof -y &>/dev/null;
fi

# delete bugged file
rm /etc/nginx/sites-enabled/default;

# create a symlink to the default file in sites-available directory instead
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default;

# try to stop and start nginx
service nginx stop &>/dev/null;

service nginx start;
