#!/usr/bin/env bash
# Find out what’s keeping an Ubuntu container’s Nginx
# installation from listening on port 80

sudo sed -i 's/\s*listen 8080 default_server;/\tlisten 80 default_server;/' /etc/nginx/sites-enabled/default;
sudo apt-get install lsof > /dev/null 2>&1;
touch /tmp/ps_file
lsof -i tcp:8080 | awk '8080{print $2}' | grep "[0-9]" -m 1 | cat > /tmp/ps_file;
pkill -F /tmp/ps_file;
rm /tmp/ps_file
sudo service nginx stop;
sudo service nginx start;
