#!/usr/bin/env bash
# Find out what’s keeping an Ubuntu container’s Nginx
# installation from listening on port 80

sed -i 's/\s*listen 8080 default_server;/\tlisten 80 default_server;/g' /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
