#!/usr/bin/env bash
# displays the contents of the file `/etc/passwd`
#+ only displays the username, user id, and user home directory path.

while read -r i
do
  echo "$i" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
